server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      force: true

# spring:
#   mustache:
#     servlet:
#       expose-session-attributes: true


spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

# mybatis:
#   mapper-locations:
#     - classpath:mapper/**.xml
#   configuration:
#     map-underscore-to-camel-case: true
